import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { fixtureStartupMs, startFixture } from './fixture.js';
let stopFixture, fixture;
test.beforeAll(async () => {
  test.setTimeout(fixtureStartupMs + 5000);
  ({ fixture, stop: stopFixture } = await startFixture());
});
test.afterAll(async () => { await stopFixture?.(); });
async function accessibility(page) {
  const report = await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
  expect(report.violations.map(({id,nodes}) => ({id,nodes:nodes.map(({target,failureSummary})=>({target,failureSummary}))}))).toEqual([]);
}
test('terminal approval, cancellation, keyboard access, reflow and private-context logout', async ({page, context}) => {
  await page.goto(`${fixture.issuer}/apps`);
  const start = page.getByRole('button', {name:/sign in with your terminal/i});
  await expect(start).toBeVisible();
  await expect(page.getByRole('heading', {name:'Sign in', exact:true})).toBeVisible();
  await expect(page).toHaveTitle('Sign in · riAuth');
  await expect(page.getByRole('complementary', {name:'Workspace navigation'})).toBeHidden();
  await expect(page.locator('#workspace-header')).toBeHidden();
  await expect(page.getByRole('button', {name:'All applications', exact:false})).toBeHidden();
  await expect(page.getByRole('searchbox', {name:'Search applications'})).toBeHidden();
  for (const width of [1280, 640, 320]) {
    await page.setViewportSize({width,height:900});
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await expect(start).toBeVisible();
  }
  await accessibility(page);
  await page.setViewportSize({width:1280,height:900});
  await start.focus();
  await page.keyboard.press('Enter');
  await expect(page.locator('#user-code')).not.toBeEmpty();
  await page.getByRole('button', {name:'Cancel sign-in'}).click();
  await expect(start).toBeVisible();
  await start.click();
  await expect(page.locator('#user-code')).not.toBeEmpty();
  const code = await page.locator('#user-code').innerText();
  const response = await page.request.post(`${fixture.issuer}/api/portal/requests/${encodeURIComponent(code)}`, {headers:{authorization:`Bearer ${fixture.token}`}, data:{approve:true}});
  expect(response.ok()).toBe(true);
  await expect(page.getByRole('link',{name:'Open Fixture application (opens in a new tab)',exact:true})).toBeVisible({timeout:15000});
  await expect(page.getByRole('complementary', {name:'Workspace navigation'})).toBeVisible();
  await expect(page.locator('#workspace-header')).toBeVisible();
  await expect(page).toHaveTitle('Your applications · riAuth');
  await accessibility(page);
  // Settings are addressable workspace pages. Link navigation keeps the
  // document, while a direct request or reload reconstructs the same page.
  await page.evaluate(() => { window.workspaceNavigationProbe = 'same document'; });
  const settings = page.locator('#settings-page');
  const settingsLink = page.getByRole('link',{name:'Settings',exact:true});
  await expect(settingsLink).toHaveAttribute('href', new URL(`${fixture.issuer}/apps/settings`).pathname);
  await settingsLink.click();
  await expect(page).toHaveURL(`${fixture.issuer}/apps/settings`);
  await expect(settings).toBeVisible();
  await expect(page.getByRole('heading',{name:'Settings',exact:true,level:1})).toBeFocused();
  await expect(page.locator('#catalogue')).toBeHidden();
  await expect(page.getByRole('dialog',{name:'Settings',exact:true})).toHaveCount(0);
  expect(await page.evaluate(() => window.workspaceNavigationProbe)).toBe('same document');
  await page.keyboard.press('Escape');
  await expect(settings).toBeVisible();
  await expect(page).toHaveURL(`${fixture.issuer}/apps/settings`);
  for (const width of [1280,640,320]) {
    await page.setViewportSize({width,height:900});
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await accessibility(page);
  }
  await page.setViewportSize({width:1280,height:900});
  const appearance = settings.getByRole('combobox',{name:'Color mode'});
  await expect(appearance).toHaveValue('system');
  await appearance.selectOption('dark');
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
  await accessibility(page);
  await settings.getByRole('link',{name:'Back to applications',exact:true}).click();
  await expect(page).toHaveURL(`${fixture.issuer}/apps`);
  await expect(settings).toBeHidden();
  await accessibility(page);
  await page.goBack();
  await expect(page).toHaveURL(`${fixture.issuer}/apps/settings`);
  await expect(settings).toBeVisible();
  await expect(page.locator('#settings-title')).toBeFocused();
  expect(await page.evaluate(() => window.workspaceNavigationProbe)).toBe('same document');
  await page.reload();
  await expect(page).toHaveURL(`${fixture.issuer}/apps/settings`);
  await expect(settings).toBeVisible();
  await expect(page.locator('#settings-title')).toBeFocused();
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
  await expect(appearance).toHaveValue('dark');
  await appearance.selectOption('light');
  await page.emulateMedia({colorScheme:'dark'});
  // Let the media change render before reversing it: Firefox coalesces changes
  // within a frame, while a user changing OS appearance triggers separate frames.
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  await expect(page.locator('html')).toHaveAttribute('data-theme','light');
  await appearance.selectOption('system');
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
  await page.emulateMedia({colorScheme:'light'});
  await expect(page.locator('html')).toHaveAttribute('data-theme','light');
  await appearance.selectOption('dark');
  const account = await context.newPage();
  await account.goto(`${fixture.issuer}/account/security`);
  await expect(account.getByRole('combobox',{name:'Color mode'})).toHaveValue('dark');
  await expect(account.locator('html')).toHaveAttribute('data-theme','dark');
  await accessibility(account);
  await account.getByRole('combobox',{name:'Color mode'}).selectOption('light');
  await expect(page.locator('html')).toHaveAttribute('data-theme','light');
  await account.close();
  const securityLink = page.locator('#settings-security');
  await expect(securityLink).toHaveAttribute('href', new URL(`${fixture.issuer}/apps/security`).pathname);
  await securityLink.click();
  const security = page.locator('#security-page');
  await expect(page).toHaveURL(`${fixture.issuer}/apps/security`);
  await expect(security).toBeVisible();
  await expect(page.getByRole('heading',{name:'Sign-in and security',exact:true,level:1})).toBeFocused();
  await expect(settings).toBeHidden();
  await expect(page.locator('#catalogue')).toBeHidden();
  await expect(page.getByRole('dialog',{name:'Sign-in and security',exact:true})).toHaveCount(0);
  await page.keyboard.press('Escape');
  await expect(security).toBeVisible();
  await expect(page).toHaveURL(`${fixture.issuer}/apps/security`);
  for (const width of [1280,640,320]) {
    await page.setViewportSize({width,height:900});
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await accessibility(page);
  }
  await page.setViewportSize({width:1280,height:900});
  await page.reload();
  await expect(page).toHaveURL(`${fixture.issuer}/apps/security`);
  await expect(security).toBeVisible();
  await expect(page.locator('#security-title')).toBeFocused();
  await page.goBack();
  await expect(settings).toBeVisible();
  await expect(security).toBeHidden();
  await page.goForward();
  await expect(security).toBeVisible();
  await expect(settings).toBeHidden();
  await expect(page.locator('#security-close')).toHaveAttribute('href', new URL(`${fixture.issuer}/apps`).pathname);
  await page.locator('#security-close').click();
  await expect(page).toHaveURL(`${fixture.issuer}/apps`);
  await expect(security).toBeHidden();
  const direct = await context.newPage();
  await direct.goto(`${fixture.issuer}/apps/security`);
  await expect(direct.locator('#security-page')).toBeVisible();
  await expect(direct.getByRole('heading',{name:'Sign-in and security',exact:true,level:1})).toBeVisible();
  await accessibility(direct);
  await direct.goto(`${fixture.issuer}/apps/settings`);
  await expect(direct.locator('#settings-page')).toBeVisible();
  await expect(direct.getByRole('combobox',{name:'Color mode'})).toHaveValue('light');
  await accessibility(direct);
  await direct.close();
  for (const width of [1280, 640, 320]) {
    await page.setViewportSize({width,height:900});
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  }
  await page.setViewportSize({width:1280,height:900});
  // 200% text scaling independently of viewport reflow.
  await page.evaluate(() => { for (const node of document.querySelectorAll('h1,h2,h3,p,a,button,input,select')) node.style.fontSize = `${parseFloat(getComputedStyle(node).fontSize)*2}px`; });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.reload();
  await expect(page.getByRole('searchbox',{name:'Search applications'})).toBeVisible();
  await page.keyboard.press('/');
  await expect(page.getByRole('searchbox',{name:'Search applications'})).toBeFocused();
  await context.setOffline(true);
  await page.getByRole('button',{name:'Refresh applications'}).click();
  await expect(page.locator('#connection-label')).toContainText(/offline|reconnect|interrupted/i);
  await expect(page.locator('#workspace-header')).toBeHidden();
  await expect(page.getByRole('button',{name:'Try again'})).toBeVisible();
  await context.setOffline(false);
  await page.getByRole('button',{name:'Try again'}).click();
  await expect(page.getByRole('link',{name:'Open Fixture application (opens in a new tab)',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Sign out'}).focus();
  await expect(page.getByRole('button',{name:'Sign out'})).toBeEnabled();
  await page.keyboard.press('Enter');
  await expect(start).toBeVisible();
  await expect(page.getByRole('heading', {name:'Sign in', exact:true})).toBeFocused();
  await expect(page.getByRole('complementary', {name:'Workspace navigation'})).toBeHidden();
  await expect(page.locator('#workspace-header')).toBeHidden();
  await expect(page).toHaveTitle('Sign in · riAuth');
  await expect(page.getByRole('link',{name:'Settings',exact:true})).toBeHidden();
  await expect(page.getByRole('link',{name:'Open Fixture application (opens in a new tab)',exact:true})).toHaveCount(0);
});
