#![recursion_limit = "256"]
#[cfg(not(feature = "essentials"))]
compile_error!("Select --features essentials or --features platform for a server build");
pub mod agent;
pub mod api;
mod assembly;
pub mod assurance;
pub mod authenticator;
pub mod authorization;
pub mod bootstrap;
pub mod browser;
pub mod claims;
pub mod cli;
pub mod cloud_directory;
pub mod config;
pub mod connector_guard;
pub mod context;
pub mod core;
pub mod crypto;
pub mod device_trust;
pub mod directory;
pub mod dpop;
pub mod edition;
pub mod encryption;
pub mod error;
pub mod event_map;
pub mod exchange;
pub mod identity;
pub mod issuer;
pub mod jose;
pub mod keyring;
pub mod kms;
mod ldap_listener;
#[cfg(feature = "platform")]
pub mod ldap_server;
#[cfg(not(feature = "platform"))]
#[path = "ldap_server_essentials.rs"]
pub mod ldap_server;
pub mod lifecycle;
pub mod logout;
pub(crate) mod management;
pub mod migration;
pub mod model;
pub mod mtls;
pub mod offboarding;
pub mod oidc;
pub mod operations;
pub mod outpost;
pub mod pam;
pub mod passkey;
pub mod portal;
pub mod postgres_store;
pub mod provider;
pub mod provisioning;
mod proxy_listener;
pub mod radius;
pub mod recovery;
pub mod registration;
pub mod reports;
pub mod resource;
pub mod response;
pub mod saml;
pub mod schema;
pub mod scim;
pub mod session_protocol;
pub mod signin;
pub mod source;
pub mod ssf;
pub mod state;
pub mod store;
pub mod telemetry;
pub mod upgrade;
pub mod windows_login;
pub mod workflow;

#[cfg(feature = "fuzzing")]
pub mod fuzzing;
#[cfg(feature = "platform")]
pub mod proxy_server;
#[cfg(not(feature = "platform"))]
#[path = "proxy_server_essentials.rs"]
pub mod proxy_server;
